### ISSUE TITLE
Hex file of Attiny404

### ISSUE THREAD

**Issue by hualazimo7** [rfmerrill/genesis_6button#1]
Can you provide the firmware of attiny404?

**Comment by rfmerrill** [comment]
It's been so long since I touched this project that I no longer am sure which revision I should build to give you a hex file, plus I have a new computer and don't have the compiler installed anymore. I might be able to get it for you in a while but I would want to be able to re-test it before I tell anyone to use it, which would mean finding one of the boards, hooking it up etc etc.

It shouldn't be too hard for you to build yourself--it's a really simple project, and Atmel Studio/Microchip Studio is free and not too hard to install.
